// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_zTMkva33YfFFPls98idjBW_JGioghg',
    appId: '1:382437652697:web:c05b12e03f86efb616a6c8',
    messagingSenderId: '382437652697',
    projectId: 'app-sagfam',
    authDomain: 'app-sagfam.firebaseapp.com',
    storageBucket: 'app-sagfam.appspot.com',
    measurementId: 'G-CCC4C11SSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFI7MZO1obsmghHBQjmSbmPZD6UUthl8U',
    appId: '1:382437652697:android:39abd56efe015ae116a6c8',
    messagingSenderId: '382437652697',
    projectId: 'app-sagfam',
    storageBucket: 'app-sagfam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHyXJtmTlthMp0gsKkZyOLXDtaYpY938Y',
    appId: '1:382437652697:ios:ea99f39b4345835f16a6c8',
    messagingSenderId: '382437652697',
    projectId: 'app-sagfam',
    storageBucket: 'app-sagfam.appspot.com',
    iosClientId: '382437652697-j69ij27mk76pule15frmd2um4imddc4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoSagfam',
  );
}
